ITInventory/Models/AssignedAssetsViewModel.cs
using System;
using System.Collections.Generic;
using ContentManagementSystem.Models;

namespace ContentManagementSystem.Models
{
    public class AssignedAssetsViewModel
    {
        public List<AssignedAssetItem> AssignedAssets { get; set; } = new List<AssignedAssetItem>();
    }

    public class AssignedAssetItem
    {
        public int MaterialOutId { get; set; }
        public string IssuanceDate { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Department { get; set; }
        public string AssetName { get; set; }
        public string SerialNo { get; set; }
        public string ModelNo { get; set; }
        public string WarrantyDate { get; set; }
        public string AssignmentDate { get; set; }
        public string Status { get; set; }

        public string Generation { get; set; }
        public string? CPUCapacity { get; set; }
        public string? HardDisk { get; set; }
        public string? RAMCapacity { get; set; }
        public string? SSDCapacity { get; set; }
        public string? Processor { get; set; }
        public string? ItemName { get; set; }
        public string? Other { get; set; }
    }
} 

ITInventory/Models/AvailableItemViewModel.cs
using System;
using System.Collections.Generic;

namespace ContentManagementSystem.Models
{
    public class AvailableItemViewModel
    {
        public string SearchTerm { get; set; }
        public DateTime? BillDateFrom { get; set; }
        public DateTime? BillDateTo { get; set; }
        public DateTime? WarrantyDateFrom { get; set; }
        public DateTime? WarrantyDateTo { get; set; }
        public List<MaterialItem> AvailableItems { get; set; }

        public AvailableItemViewModel()
        {
            AvailableItems = new List<MaterialItem>();
        }
    }
} 

ITInventory/Models/AvailableStockViewModel.cs
using System;
using System.Collections.Generic;

namespace ContentManagementSystem.Models
{
    public class AvailableStockViewModel
    {
        public string SearchTerm { get; set; }
        public DateTime? ReceivedDateFrom { get; set; }
        public DateTime? ReceivedDateTo { get; set; }
        public List<MaterialItem> Materials { get; set; }
       
           public IEnumerable<MaterialItem> MaterialItems { get; set; }
        

    
}
} 

ITInventory/Models/Material.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

using System.Globalization;
using Microsoft.AspNetCore.Mvc;

namespace ContentManagementSystem.Models
{
    public class Material
    {
        private DateTime _billDate;

        public Material()
        {
            MaterialItems = new List<MaterialItem>();
           // RecordDate = DateTime.Now;  // Set default value
        }

        
        public string Id { get; set; }
        
        [Required]
        public int CompanyId { get; set; }
        
        [Required]
        public int AssetItemId { get; set; }
        
        public int? VendorId { get; set; }
        
        public int? ManufacturerId { get; set; }

        
        // Custom names for Other types
        [Display(Name = "Custom Vendor")]
        public string CustomVendorName { get; set; }
        
        [Display(Name = "Custom Manufacturer")]
        public string CustomManufacturerName { get; set; }
        
        [Display(Name = "Custom Asset")]
        public string CustomAssetName { get; set; }
        
        [Required(ErrorMessage = "Invoice Number is required")]
        [Display(Name = "Invoice No")]
        public string InvoiceNo { get; set; }
        
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [ModelBinder(BinderType = typeof(CustomDateTimeModelBinder))]
        public string BillDate 
        { 
            get;
            set ;
        }
        
        [NotMapped]
        public string BillDateString
        {
            get => _billDate.ToString("dd/MM/yyyy");
            set
            {
                if (DateTime.TryParseExact(value, "dd/MM/yyyy", 
                    CultureInfo.InvariantCulture, 
                    DateTimeStyles.None, 
                    out DateTime date))
                {
                    _billDate = date;
                }
            }
        }
        
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than 0")]
        [Display(Name = "REQN Quantity")]
        public int ReqnQuantity { get; set; }
        
        public string ImagePath { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string RecordDate { get; set; }

        // Navigation properties
        public string Company { get; set; }
        public string AssetItem { get; set; }
        public string Vendor { get; set; }
        public string Manufacturer { get; set; }
        public string TotalItem { get; set; }
        public virtual ICollection<MaterialItem> MaterialItems { get; set; }
    }


    


    /*
    public class MaterialItem
    {
        public MaterialItem()
        {
            Status = "UnAssigned";  // Set default value
        }

        public int Id { get; set; }
        public int MaterialId { get; set; }
        
        public string Status { get; set; }
        
        // Common fields
        [Required]
        public string SerialNo { get; set; }
        [Required]
        public string ModelNo { get; set; }
        
        // Fields for Desktop/Laptop
        public string Generation { get; set; }
        public int? CPUCapacity { get; set; }
        public int? HardDisk { get; set; }
        public int? RAMCapacity { get; set; }
        public int? SSDCapacity { get; set; }
        public string Other { get; set; }
        
        // Fields for Other items
        public string ItemName { get; set; }
        [Display(Name = "Warranty Date")]
        public DateTime? WarrantyDate { get; set; }

        public Material Material { get; set; }
    }
    */

    
} 

ITInventory/Models/MaterialOut.cs
using System;
using ContentManagementSystem.Models;

namespace ContentManagementSystem.Models
{
    public class MaterialOut
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public string EmployeeId { get; set; }
        public DateTime IssuanceDate { get; set; }
        public string Remarks { get; set; }

        public virtual Company Company { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Employee Employee { get; set; }
    }
} 

ITInventory/Models/MaterialViewModel.cs
using System.Collections.Generic;

namespace ContentManagementSystem.Models
{
    public class MaterialViewModel
    {
        public MaterialViewModel()
        {
            Materials = new List<Material>();
            NewMaterial = new Material();
        }

        public List<Material> Materials { get; set; }
        public Material NewMaterial { get; set; }
        public string SearchTerm { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string ReceivedDateFrom { get; set; }
        public string ReceivedDateTo { get; set; }
    }
}

ITInventory/Controllers/MaterialController.cs
using ContentManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;

using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System.Globalization;
using System.Linq.Expressions;
using Microsoft.VisualBasic;
using GuardTour;
using System.Data;
using System.Text.Json.Nodes;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using static ContentManagementSystem.Filters.AuthenticationFilter;
using ContentManagementSystem.Filters;

namespace ContentManagementSystem.Controllers
{
    [AuthenticationFilter]
    public class MaterialController : Controller
    {
       db_Utility util=new db_Utility();
       

        public IActionResult Index()
        {
            try

            {
              


                ViewBag.Companies = util.PopulateDropDown("select * from Companies where id=1", util.strElect);
                ViewBag.AssetItems = util.PopulateDropDown("select * from AssetItems", util.strElect);
                ViewBag.Vendors = util.PopulateDropDown("select * from Vendors", util.strElect);
                ViewBag.Manufacturers = util.PopulateDropDown("select * from Manufacturers", util.strElect);





                return View();
            }
            catch (Exception ex)
            {
               
                return View();
            }
        }

       

        private DateTime? ParseDate(string dateStr)
        {
            if (string.IsNullOrEmpty(dateStr))
                return null;

            try
            {
                var dateParts = dateStr.Split('/');
                if (dateParts.Length == 3)
                {
                    int day = int.Parse(dateParts[0]);
                    int month = int.Parse(dateParts[1]);
                    int year = int.Parse(dateParts[2]);
                    return new DateTime(year, month, day);
                }
            }
            catch (Exception ex)
            {
                
            }
            return null;
        }

        [HttpPost]
        public IActionResult Addnew(IFormFile? file)
        {
            try
            {
                string Invoice = Request.Form["Invoice"].ToString();
                string Companyid = Request.Form["Companyid"].ToString();
                string AssetItem = Request.Form["AssetItem"].ToString();
                string customAssetName = Request.Form["customAssetName"].ToString();
                string Vendor = Request.Form["Vendor"].ToString();
                string customVendorName = Request.Form["customVendorName"].ToString();
                string Manufacturer = Request.Form["Manufacturer"].ToString();
                string customManufacturerName = Request.Form["customManufacturerName"].ToString();
                string BillDate = Request.Form["BillDate"].ToString();
               

                
                string ReceivedDate = Request.Form["ReceivedDate"].ToString();
                string reqnQuantity = Request.Form["reqnQuantity"].ToString();
                //string invoiceUpload = Request.Form["FileName"].ToString();
                string JsonData = Request.Form["JsonData"].ToString();
                var objects = JArray.Parse(JsonData);
                string Id = "";
                string Metrailno = "";
                string fileName = "";
                foreach (var e in objects)
                {
                    var ds2 = util.Fill(@$"exec ChekcSerailNo @SerialNo='{e["SerialNo"]}' ", util.strElect);
                   int  no = Convert.ToInt32(ds2.Tables[0].Rows[0][0]);
                    if(no >0)
                    {
                        Id = "Duplicate Serial No : " + e["SerialNo"];
                    }
                    
                    



                }

                
                if (file != null && file.Length > 0)
                {
                    string uploadsFolder = Path.Combine("wwwroot", "uploads");
                    Directory.CreateDirectory(uploadsFolder); // Ensure directory exists

                    string uniqueFileName = $"{Guid.NewGuid()}_{Path.GetFileName(file.FileName)}";
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    fileName = "uploads/"+uniqueFileName;

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                  
                }

                if (Id == "")
                {
                var ds = util.Fill(@$"exec MatrialInMaster @Invoiceno='{Invoice}',@Company='{Companyid}',@assetitem='{AssetItem}',@cusassetname='{customAssetName}',@vendor='{Vendor}',@cusvendorname='{customVendorName}',@manufacture='{Manufacturer}',@cusmanufacture='{customManufacturerName}',@billdate='{BillDate}',@Receiveddate='{ReceivedDate}',@reciveqty='{reqnQuantity}',@InvoiceImg='{fileName}' ", util.strElect);
                   
                Id = ds.Tables[0].Rows[0][0].ToString();
                    if (Id != "Invoice No Exist")
                    {
                        Metrailno = Id;
                        Id = "";
                    }
                }
                if (Id == "")
                {
                    DataSet ds1 = new DataSet();
                    foreach(var e in objects)
                    {

                   ds1=util.Fill(@$"exec MatrialItems @Materialid='{Metrailno}',@Asstitemid='{e["AssetItemId"]}',@SerialNo='{e["SerialNo"]}',@Modelno='{e["ModelNo"]}',@Gen='{e["Generation"]}',@harddisk='{e["HardDisk"]}',@RamCap='{e["RAMCapacity"]}',@SSD='{e["SSDCapacity"]}',@Other='{e["Other"]}',@ItemName='{e["ItemName"]}',@Warrantydate='{e["warrantydate"]}',@Processs='{e["CPUCapacity"]}' ", util.strElect);
                    }

                    Id = "Matrial In SuccessFully";
                }

                // Save the data to the database, etc.

                return Json(new { success = true, message = Id });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }   [HttpPost]
        public IActionResult MaterialOutInsert()
        {
            try
            {
                
                string Companyid = Request.Form["Company"].ToString();
                string branch = Request.Form["branch"].ToString();
               
                string Empid = Request.Form["employeeId"].ToString();
                string Empname = Request.Form["EmployeeName"].ToString();
                string Empemail = Request.Form["EmailId"].ToString();
                string Empdpt = Request.Form["Department"].ToString();
                string remark = Request.Form["Remarks"].ToString();
                string Empphone = Request.Form["PhoneNo"].ToString();
                string issrancedate = Request.Form["IssuanceDate"];

                string JsonData = Request.Form["JsonData"].ToString();
                var objects = JArray.Parse(JsonData);
                string Id = "";
                string Metrailno = "";
                

                

                var ds = util.Fill(@$"exec Usp_MatrialOut @branch='{branch}',@Company='{Companyid}',@EmpId='{Empid}',@IssuanceDate='{issrancedate}',@remark='{remark}',@empName='{Empname}',@empDept='{Empdpt}',@empEmail='{Empemail}',@empPhone='{Empphone}' ", util.strElect);
                   
               int outid = Convert.ToInt32(ds.Tables[0].Rows[0][0].ToString());
                    if (outid >0)
                    {
                        DataSet ds1 = new DataSet();
                        foreach (var e in objects)
                        {

                            ds1 = util.Fill(@$"exec Usp_Assignment @EmpId='{Empid}' ,@serailno='{e["serailno"]}', @WindowsKey='{e["windowskey"]}',@MSOfficeKey='{e["msofficekey"]}', @id='{outid}',@matreailId='{e["matreailId"]}' ", util.strElect);
                        }

                      

                        Id = "Matrial Out SuccessFully";
                    }
                
                //if (Id == "")
                //{
                //    DataSet ds1 = new DataSet();
                //    foreach(var e in objects)
                //    {

                //   ds1=util.Fill(@$"exec MatrialItems @Materialid='{Metrailno}',@Asstitemid='{e["AssetItemId"]}',@SerialNo='{e["SerialNo"]}',@Modelno='{e["ModelNo"]}',@Gen='{e["Generation"]}',@harddisk='{e["HardDisk"]}',@RamCap='{e["RAMCapacity"]}',@SSD='{e["SSDCapacity"]}',@Other='{e["Other"]}',@ItemName='{e["ItemName"]}',@Warrantydate='{e["warrantydate"]}',@Processs='{e["CPUCapacity"]}' ", util.strElect);
                //    }

                //    Id = "Matrial In SuccessFully";
                //}

                // Save the data to the database, etc.

                return Json(new { success = true, message = Id });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }
        [HttpPost]
        public IActionResult ReMaterialOutInsert()
        {
            try
            {
                
                string Companyid = Request.Form["Company"].ToString();
                string branch = Request.Form["branch"].ToString();
               
                string Empid = Request.Form["employeeId"].ToString();
                string Empname = Request.Form["EmployeeName"].ToString();
                string Empemail = Request.Form["EmailId"].ToString();
                string Empdpt = Request.Form["Department"].ToString();
                string remark = Request.Form["Remarks"].ToString();
                string Empphone = Request.Form["PhoneNo"].ToString();

ITInventory/Views/Material/AssetAssignmentDetails.cshtml
@using System.Data

@{
    ViewData["Title"] = "Asset Assignment Details";
    var dt = ViewBag.data as DataTable;
}

<div class="container-fluid">
    

    <div class="row">
        <!-- Sidebar -->
        @await Html.PartialAsync("_Sidebar")

        <!-- Main content -->
        <div id="div" class="col-md-10">
            <div id="divcont" class="container mt-4">
                <h3>Asset Assignment Details</h3>


                @Html.AntiForgeryToken()
                @using (Html.BeginForm("AssetAssignmentDetails", "Material", FormMethod.Get))
                {
                <div class="row">

                    <div class="col-md-4">
                        <div class="form-group mb-3">
                            <label>Asset Name</label>


                                <select name="asset" class="form-control" id="Asset" onchange="bindserailno(this.value)" style="border: 1px solid lightgray;">

                                @if (ViewBag.AssetItems != null)

                                {
                                    <option value="0">Select</option>

                                    foreach (var item in ViewBag.AssetItems as List<SelectListItem>)

                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }

                                }
                            </select>

                           

                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group mb-3">
                            <label>Serial No</label>


                            <select name="serialno" class="form-control " id="serialno" style="border: 1px solid lightgray;">

                                @if (ViewBag.SerialNo != null)

                                {
                                    <option value="0">Select</option>

                                    foreach (var item in ViewBag.SerialNo as List<SelectListItem>)

                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }

                                }
                            </select>

                            <input type="text" id="employeeId" placeholder="Employee ID" class="form-control d-none" />

                        </div>
                    </div>
                    <div class="col-md-2">
                        


                            <div class="form-group mb-3">
                                <label></label>
                        <button type="submit" class="btn btn-primary mt-4">Search</button>
                                <button onclick="exportexcel()" class="btn btn-primary mt-4">Excel</button>

                        </div>
                        </div>
                </div>
                }
               

                <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

                <table id="itemsTable" class="display table table-bordered">
                    <thead>
                        <tr>
                            @foreach (System.Data.DataColumn col in dt.Columns)
                            {
                                <th>@col.ColumnName</th>
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (System.Data.DataRow row in dt.Rows)
                        {
                            <tr>
                                @foreach (var item in row.ItemArray)
                                {
                                    <td>@item</td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>

               

               
                </div>





        </div>
    </div>
</div>


@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

  

    <script>
        function exportexcel(type, fn, dl) {

            var ddd = 'Asset Assignment Details';
            var elt = document.getElementById('itemsTable');
            console.log(elt);
            var wb = XLSX.utils.table_to_book(elt, { sheet: "sheet1" });


            return dl ?
                XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }) :
                XLSX.writeFile(wb, fn || (ddd + '.' + (type || 'xlsx')));

            // XLSX.writeFile(wb, fn || (ddd+ (type+ '.' || 'xlsx')));
        }




        function geturl() {
            let url = window.location.hostname;
            if (url == 'localhost') {
                return '';
            }
            else
                return '/itinventory';
        }

        let myurl = geturl();

        $("#Asset").select2();
        $("#serialno").select2();

        function bindserailno(e) {
        
            $.ajax({
                url: myurl + '/Material/GetSearilNO',
                type: "get",
                data: { assentid: e },
                success: function (data) {
              
                    var data = JSON.parse(data);
                    
                    var dropdown = $("#serialno");
                    dropdown.empty();
                    dropdown.append($('<option></option>').attr('value', 0).text('Select'));
                    for (var i = 0; i < data.length; i++) {

                        dropdown.append($('<option></option>').attr('value', data[i].Value).text(data[i].Text));
                    }
                },
                error: (err) => {
                    alert(err)
                }
            })


        };


    </script>

    <style>
        .select2-container {
            width: 100% !important;
        }

        .select2-selection {
            height: 38px !important;
            padding: 5px !important;
            border: 1px solid #ced4da !important;
            border-radius: 0.25rem !important;
        }

        .select2-selection__arrow {
            height: 36px !important;
        }

        .select2-search__field {
            width: 100% !important;
        }

        .select2-results__option {
            padding: 8px !important;
        }

        .select2-container--default .select2-selection--single {
            border: 1px solid #ced4da !important;
        }

            .select2-container--default .select2-selection--single .select2-selection__rendered {
                line-height: 26px !important;
            }

        select:disabled {
            background-color: #e9ecef;
            cursor: not-allowed;
        }

        .loading-select {
            position: relative;
        }

            .loading-select::after {
                content: "Loading...";
                position: absolute;
                right: 30px;
                top: 50%;
                transform: translateY(-50%);
                font-size: 12px;
                color: #6c757d;
            }

        .branch-select-container {
            position: relative;
        }

            .branch-select-container .select2-container {
                width: 100% !important;
            }

            .branch-select-container .select2-selection {
                height: 38px !important;
                padding: 5px !important;
                border: 1px solid #ced4da !important;
                border-radius: 0.25rem !important;
            }

            .branch-select-container .select2-selection__arrow {
                height: 36px !important;
            }

            .branch-select-container .select2-selection__placeholder {
                color: #6c757d;
            }

            .branch-select-container .select2-selection__rendered {
                line-height: 26px !important;
            }

            .branch-select-container .input-group .btn {
                border-color: #ced4da;
            }

                .branch-select-container .input-group .btn:hover {
                    background-color: #e9ecef;
                }

      

        .invalid-feedback {
            display: block;
            width: 100%;
            margin-top: 0.25rem;
            font-size: 0.875em;
            color: #dc3545;
        }

        
    </style>
}

ITInventory/Views/Material/Returnasset.cshtml
@{
    ViewData["Title"] = "Returnasset";
}

<h1>Returnasset</h1>

;